### ISSUE TITLE
Notities afronden (FE en BE)

### ISSUE THREAD

**Issue by peterboer** [Amsterdam/fixxx-looplijsten-frontend#336]
- [x] Backend: aanpassen fieldname " video-call' naar 'intercom' (@petercuret / @xavierbloemen )
- [x] Frontend: testen Android/iOS (bevindingen in Bugs-kolom graag)
- [x] Frontend: opschonen code
- [x] Backend: Volledig overschrijven van data bij editen

**Comment by xavierbloemen** [comment]
https://github.com/Amsterdam/fixxx-looplijsten-backend/pull/106
