### ISSUE TITLE
notitie module comform style guide maken (FE)

### ISSUE THREAD

**Issue by NvElten-UX** [Amsterdam/fixxx-looplijsten-frontend#357]
- [ ] Titels en hints omdraaien. Label is de vraag dik zwarte gedrukt met evt. (niet verplicht). hint is grijs eronder met toelichting op de vraag. (in praktijk dus teksten veelal omdraaien)

- [ ] radio buttons comform Primairy button component (blauw ipv zwart wanneer selected)

**Comment by peterboer** [comment]
verplaatst naar Jira
